# Generated by Django 2.0.4 on 2018-04-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letters',
            name='Audio',
            field=models.FileField(blank=True, null=True, upload_to='songclips', verbose_name='Upload Audio Ex: A for Apple'),
        ),
        migrations.AddField(
            model_name='letters',
            name='correct',
            field=models.ImageField(null=True, upload_to='pics', verbose_name='Enter the correct Image'),
        ),
        migrations.AddField(
            model_name='letters',
            name='correct_name',
            field=models.CharField(max_length=20, null=True, verbose_name='Upload the name of the correct object'),
        ),
        migrations.AddField(
            model_name='letters',
            name='incorrect1',
            field=models.ImageField(null=True, upload_to='pics', verbose_name='Upload 1st incorrect Image'),
        ),
        migrations.AddField(
            model_name='letters',
            name='incorrect2',
            field=models.ImageField(null=True, upload_to='pics', verbose_name='Upload 2nd incorrect Image'),
        ),
        migrations.AddField(
            model_name='letters',
            name='incorrect3',
            field=models.ImageField(null=True, upload_to='pics', verbose_name='Upload 3rd incorrect Image'),
        ),
        migrations.AddField(
            model_name='letters',
            name='name',
            field=models.CharField(max_length=1, null=True, verbose_name='Enter A letter'),
        ),
    ]
