# Generated by Django 2.0.4 on 2018-04-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_letters_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letters',
            name='message',
            field=models.CharField(max_length=20, null=True, verbose_name='Enter the text : Ex: A FOR APPLE'),
        ),
    ]
